apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hossein-controller-jobs
  namespace: monarch-tests
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hossein-controller-jobs
  namespace: monarch-tests
subjects:
  - kind: ServiceAccount
    name: hossein-controller
    namespace: monarch-tests
roleRef:
  kind: Role
  name: hossein-controller-jobs
  apiGroup: rbac.authorization.k8s.io
