name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - "linux.4xlarge.nvidia.gpu"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          set -eux

          sudo apt-get install -y protobuf-compiler

          pip install -e .[dev] -v
      - name: Run Python Tests
        run: |
          set -eux

          pytest -v
      - name: Run Rust Lint
        run: |
          set -eux

          cargo test -v

