name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        include:
          - runs-on: "linux.2xlarge"
            gpu-arch-type: "cpu"
            gpu-arch-version: ""
          - runs-on: "linux.4xlarge.nvidia.gpu"
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"

    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      timeout: 120
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      script: |
        set -ex

        # install python and protobuf
        conda create -n venv python=3.10 protobuf -y
        conda activate venv
        python -m pip install --upgrade pip

        # install recent version of Rust via rustup
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=default -y
        . "$HOME/.cargo/env"

        pip install -e .[dev] -v

        pytest -v
        cargo test -v

